# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx
  - windows

before_script:
  # "npm link" the module so ESLint can find it
  - npm link
  - npm link eslint-config-modular

script: npm test
