# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: 6
    - node_js: 8
    - node_js: 10

before_script:
  # "npm link" the module so ESLint can find it
  - npm link
  - npm link eslint-config-modular

script:
  - npm test
